#!/bin/sh

set -e

echo "      _       _         __ _ _"
echo "   __| | ___ | |_      / _(_) | ___  ___"
echo "  / _\` |/ _ \| __|____| |_| | |/ _ \/ __|"
echo " | (_| | (_) | ||_____|  _| | |  __/\__ \\"
echo "  \__,_|\___/ \__|    |_| |_|_|\___||___/"
echo ""

echo "==> Here we go..."
cd ~

echo "  > Fetching dependencies ..."
echo "vim plugged"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "oh-my-zsh"
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo "tpm"
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

echo "base16"
git clone https://github.com/chriskempson/base16-shell.git ~/.qbase16/base16-shell

echo "zsh syntax highlighting, auto suggestion & zsh-z"
git clone https://github.com/zsh-users/zsh-autosuggestions.git $HOME/.oh-my-zsh/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/plugins/zsh-syntax-highlighting
git clone https://github.com/agkozak/zsh-z $HOME/.oh-my-zsh/plugins/zsh-z

echo "==> Done with setup."
