#!/bin/sh

set -e

echo "      _       _         __ _ _"
echo "   __| | ___ | |_      / _(_) | ___  ___"
echo "  / _\` |/ _ \| __|____| |_| | |/ _ \/ __|"
echo " | (_| | (_) | ||_____|  _| | |  __/\__ \\"
echo "  \__,_|\___/ \__|    |_| |_|_|\___||___/"
echo ""

echo "==> Here we go..."
cd ~

echo "  > Updating all git submodules..."
# git submodule init &> /dev/null
# git submodule update &> /dev/null
#sudo apt-get install $(grep -vE "^#" .myapts )

echo "updating shell colors"
#git clone https://github.com/chriskempson/base16-shell.git
cd base16-shell
sh base16-ocean.dark.sh
#~/base16-shell/base16-ocean.dark.sh
echo "shell colo update complete"

echo "==> Done with setup."
